# **Fisik vs. Digital: Analisis Perbandingan Kerentanan Media Penyimpanan Data Kesehatan US**
Kelompok 2:
1. Adhitya Bayu Pratama   : 5027261045
2. Via Nur Belaya         : 5027261060
3. Raditya Langit Nugraha : 5027261072
*Topik: Data Breaches*

Data ini sangat menarik untuk diteliti karena tidak hanya memetakan jenis-jenis media penyimpanan data kesehatan yang paling rentan mengalami kebocoran, tetapi juga mengungkap secara pasti seberapa besar jumlah individu yang dirugikan dari setiap insiden tersebut. Dari temuan tersebut, analisis ini disusun untuk menjawab beberapa pertanyaan yang muncul guna memahami pola, karakteristik, dan tingkat keparahan risiko keamanan data medis secara menyeluruh yaitu:
- Berapa perbandingan proporsi dan frekuensi insiden kebocoran data antara media dokumen fisik (paper records) dan perangkat elektronik?
- Bagaimana distribusi jenis pelanggaran (Type of Breach) pada media fisik dibandingkan dengan digital?
- Tipe entitas kesehatan (Covered Entity Type) mana yang paling sering mengalami kebocoran data pada media dokumen fisik versus perangkat elektronik?

In [9]:
import pandas as pd # untuk manipulasi, pembersihan, dan analisis data terstruktur
import numpy as np # untuk melakukan komputasi numerik, matematika, dan ilmiah dalam skala besar
import matplotlib as mt # untuk membuat visualisasi data
import seaborn as sns # fungsinya mirip matplotlib yaitu untuk visualisasi data

pd.set_option("display.max_columns", None)

print("Library berhasil di-import.")

Library berhasil di-import.

In [10]:
df = pd.read_csv('breach_report.csv', index_col=0) 
print("Jumlah baris, kolom:", df.shape) 

pd.set_option('display.max_rows', None) #tampilkan semua data yg di read tanpa limit

Jumlah baris, kolom: (1654, 9)

In [11]:
df.head() # untuk display 5 baris utama

,Name of Covered Entity,State,Covered Entity Type,Individuals Affected,Breach Submission Date,Type of Breach,Location of Breached Information,Business Associate Present,Web Description
index,,,,,,,,,
0,Brooke Army Medical Center,TX,Healthcare Provider,1000.0,10/21/09,Theft,Paper/Films,No,A binder containing the protected health infor...
1,"Mid America Kidney Stone Association, LLC",MO,Healthcare Provider,1000.0,10/28/09,Theft,Network Server,No,Five desktop computers containing unencrypted ...
2,Alaska Department of Health and Social Services,AK,Healthcare Provider,501.0,10/30/09,Theft,"Other, Other Portable Electronic Device",No,\N
3,Health Services for Children with Special Need...,DC,Health Plan,3800.0,11/17/09,Loss,Laptop,No,A laptop was lost by an employee while in tran...
4,"Mark D. Lurie, MD",CA,Healthcare Provider,5166.0,11/20/09,Theft,Desktop Computer,No,A shared Computer that was used for backup was...

Setiap baris menjelaskan satu rumah sakit yang terkena data breach.

In [12]:
df.info()                 # tipe data setiap kolom

<class 'pandas.DataFrame'>
RangeIndex: 1654 entries, 0 to 1653
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Name of Covered Entity            1654 non-null   str
 1   State                             1645 non-null   str
 2   Covered Entity Type               1613 non-null   str
 3   Individuals Affected              1632 non-null   float64
 4   Breach Submission Date            1654 non-null   str
 5   Type of Breach                    1640 non-null   str
 6   Location of Breached Information  1643 non-null   str
 7   Business Associate Present        1654 non-null   str
 8   Web Description                   1257 non-null   str
dtypes: float64(1), str(8)
memory usage: 116.4 KB

In [13]:
df.isna().sum()           # jumlah data kosong per kolom

Name of Covered Entity                0
State                                 9
Covered Entity Type                  41
Individuals Affected                 22
Breach Submission Date                0
Type of Breach                       14
Location of Breached Information     11
Business Associate Present            0
Web Description                     397
dtype: int64

In [14]:
print(df.duplicated().sum())     # jumlah baris duplikat

1

In [15]:
df[df['Type of Breach'].isna()]

,Name of Covered Entity,State,Covered Entity Type,Individuals Affected,Breach Submission Date,Type of Breach,Location of Breached Information,Business Associate Present,Web Description
index,,,,,,,,,
44,Wyoming Department of Health,WY,Health Plan,9023.0,3/2/10,NaN,Network Server,No,\N
54,"Computer Program and Systems, Inc. (CPSI)",AL,Business Associate,768.0,3/30/10,NaN,Email,Yes,\N
120,Aetna,CT,Health Plan,6372.0,7/27/10,NaN,Paper/Films,No,\N
314,Memorial Health Systems,CO,NaN,NaN,7/15/11,NaN,NaN,No,NaN
428,St. Joseph Health System,CA,NaN,NaN,2/15/12,NaN,NaN,No,NaN
566,Indiana University,IN,NaN,NaN,11/5/12,NaN,NaN,No,An unencrypted and password protected laptop c...
621,"StandfordSchoolMedicine& LP Children Hosp, Pri...",CA,NaN,NaN,1/23/13,NaN,NaN,No,NaN
660,M&C Children's Clinic PA,TX,NaN,NaN,3/19/13,NaN,NaN,No,"On March 19, 2013, the covered entity (CE), M ..."
732,Illinois Department of Healthcare and Family S...,IL,NaN,NaN,7/15/13,NaN,NaN,No,NaN
740,Louisiana State University Health Care Service...,LA,NaN,NaN,7/25/13,NaN,NaN,No,Electronic protected health information (ePHI)...
883,"Alamo Consumer Direct, LLC",TX,NaN,NaN,1/16/14,NaN,NaN,No,NaN
1128,"Indian Health Service, Aberdeen Area Office",SD,NaN,NaN,11/13/14,NaN,NaN,No,NaN
1154,Northwestern Memorial HealthCare,IL,NaN,NaN,12/23/14,NaN,NaN,No,NaN
1161,Henry Ford Health System,MI,NaN,NaN,1/9/15,NaN,NaN,No,NaN

In [16]:
df[df['State'].isna()]

,Name of Covered Entity,State,Covered Entity Type,Individuals Affected,Breach Submission Date,Type of Breach,Location of Breached Information,Business Associate Present,Web Description
index,,,,,,,,,
123,Mercer,NaN,Business Associate,1073.0,7/30/10,Loss,Other,Yes,\N
180,Puerto Rico Department of Health - Triple S Ma...,NaN,Health Plan,475000.0,11/4/10,Unauthorized Access/Disclosure,Network Server,Yes,"On November 5, 2010, the Puerto Rico Departmen..."
200,Hospital Auxilio Mutuo,NaN,Healthcare Provider,1000.0,12/13/10,Theft,"Desktop Computer, Laptop",No,"The covered entity (CE), Hospital Auxilio Mutu..."
240,Departamento de Salud de Puerto Rico,NaN,Healthcare Provider,2621.0,2/22/11,Loss,Desktop Computer,No,\N
280,"MMM Healthcare, Inc.",NaN,Healthcare Provider,32390.0,5/9/11,Theft,Desktop Computer,No,\N
356,MAPFRE Life,NaN,NaN,2209.0,9/29/11,Theft,Other,No,\N
966,Administracion de Seguros de Salud - Triple S ...,NaN,NaN,46473.0,4/15/14,Theft,Other Portable Electronic Device,Yes,"On March 27, 2014, the covered entity (CE), Pu..."
1036,Administracion de Seguros de Salud - Triple S ...,NaN,Health Plan,7911.0,7/18/14,Unauthorized Access/Disclosure,Other Portable Electronic Device,No,"On April 15, 2014, the covered entity (CE), Pu..."
1245,Puerto Rico Department of Heatlh - Medicaid Pr...,NaN,Health Plan,500.0,4/22/15,Theft,Desktop Computer,No,NaN

dari 10 kolom berikut kami akan menghapus kolom 'Name of Covered Entity', 'Breach Submission Date', 'Business Associate Present', dan 'Web Description'. Karena beberapa kolom terseebut tidak relevan dengan tujuan kita menganalisis data ini, terdapat missing value, dan semacam duplikat.

In [17]:
df = df.drop(['Name of Covered Entity','Breach Submission Date','Business Associate Present','Web Description'], axis=1)

In [18]:
df.head()

,State,Covered Entity Type,Individuals Affected,Type of Breach,Location of Breached Information
index,,,,,
0,TX,Healthcare Provider,1000.0,Theft,Paper/Films
1,MO,Healthcare Provider,1000.0,Theft,Network Server
2,AK,Healthcare Provider,501.0,Theft,"Other, Other Portable Electronic Device"
3,DC,Health Plan,3800.0,Loss,Laptop
4,CA,Healthcare Provider,5166.0,Theft,Desktop Computer

In [19]:
df = df.dropna()
df[df['Type of Breach'].isna()]

Empty DataFrame
Columns: [State, Covered Entity Type, Individuals Affected, Type of Breach, Location of Breached Information]
Index: []

hilang deh missing valuenya

In [20]:
col_to_split = 'Type of Breach'
col_to_split1 = 'Location of Breached Information'
df[col_to_split] = df[col_to_split].astype(str).str.split(', ')
df[col_to_split1] = df[col_to_split1].astype(str).str.split(', ')
df_exploded = df.explode(col_to_split).reset_index(drop=True)
df_exploded = df.explode(col_to_split1).reset_index(drop=True)
df.head()

,State,Covered Entity Type,Individuals Affected,Type of Breach,Location of Breached Information
index,,,,,
0,TX,Healthcare Provider,1000.0,[Theft],[Paper/Films]
1,MO,Healthcare Provider,1000.0,[Theft],[Network Server]
2,AK,Healthcare Provider,501.0,[Theft],"[Other, Other Portable Electronic Device]"
3,DC,Health Plan,3800.0,[Loss],[Laptop]
4,CA,Healthcare Provider,5166.0,[Theft],[Desktop Computer]

**a) Mean, Median, Modus kolom 'Individuals Affected'**

Capping data karena terdapat outlier (terlalu tinggi perbedaan minimal dan maksimalnya)

In [21]:
df['Individuals Affected'] = df['Individuals Affected'].clip(upper=200000) #basically ngecap manual di 200 ribu

In [22]:
kolom = df['Individuals Affected']
kolom.mean(), kolom.median(), kolom.mode()[0]
kolom.var(), kolom.std()
kolom.quantile(0.25), kolom.quantile(0.75)
df.describe()

       Individuals Affected
count           1592.000000
mean           13693.902010
std            37057.476781
min              500.000000
25%              985.000000
50%             2291.500000
75%             7470.750000
max           200000.000000

**b) Mean, Median, Modus kolom 'Type of Breach'**

diubah menjadi kolom numerik

In [23]:
type_mapping = {
    'Theft': 1,
    'Loss': 2,
    'Other': 3,
    'Hacking/IT Incident': 4,
    'Improper Disposal': 5,
    'Unauthorized Access/Disclosure': 6
}
df_exploded['Type of Breach Code'] = df_exploded['Type of Breach'].str[0].map(type_mapping) #di apply ke df_exploded dan diubah ke bentuk string
df_exploded.head()
df_exploded.drop(['Type of Breach Code'],axis=1) #ini tadi ke double run jadi di hapus tiap di run code nya

,State,Covered Entity Type,Individuals Affected,Type of Breach,Location of Breached Information
0,TX,Healthcare Provider,1000.0,[Theft],Paper/Films
1,MO,Healthcare Provider,1000.0,[Theft],Network Server
2,AK,Healthcare Provider,501.0,[Theft],Other
3,AK,Healthcare Provider,501.0,[Theft],Other Portable Electronic Device
4,DC,Health Plan,3800.0,[Loss],Laptop
5,CA,Healthcare Provider,5166.0,[Theft],Desktop Computer
6,CA,Healthcare Provider,5257.0,[Theft],Desktop Computer
7,CA,Healthcare Provider,857.0,[Theft],Desktop Computer
8,CA,Healthcare Provider,6145.0,[Theft],Desktop Computer
9,CA,Healthcare Provider,952.0,[Theft],Desktop Computer
10,CA,Healthcare Provider,5900.0,[Theft],Laptop
11,PA,Healthcare Provider,943.0,[Theft],Laptop
12,TN,Business Associate,6400.0,[Theft],Laptop
13,VA,Business Associate,83000.0,[Other],Paper/Films
14,CA,Healthcare Provider,596.0,[Theft],Other
15,NC,Business Associate,2000.0,[Theft],Desktop Computer
16,NC,Business Associate,2000.0,[Theft],Electronic Medical Record
17,NC,Business Associate,2000.0,[Theft],Network Server
18,MI,Healthcare Provider,646.0,[Theft],Desktop Computer
19,MI,Healthcare Provider,646.0,[Theft],Laptop
20,MI,Healthcare Provider,10000.0,[Theft],Other Portable Electronic Device
21,CA,Healthcare Provider,610.0,[Other],Email
22,MA,Business Associate,1860.0,[Theft],Electronic Medical Record
23,MA,Business Associate,1860.0,[Theft],Other
24,MA,Business Associate,1860.0,[Theft],Other Portable Electronic Device
25,DC,Business Associate,3400.0,[Theft],Paper/Films
26,MA,Healthcare Provider,1076.0,[Theft],Other
27,MD,Business Associate,15000.0,[Theft],Paper/Films
28,CA,Healthcare Provider,15500.0,[Theft],Other
29,CA,Healthcare Provider,15500.0,[Theft],Other Portable Electronic Device
30,ID,Business Associate,2562.0,[Theft],Other
31,MI,Healthcare Provider,10000.0,[Theft],Other
32,TX,Healthcare Provider,3800.0,[Loss],Other
33,TX,Healthcare Provider,3800.0,[Loss],Other Portable Electronic Device
34,MO,Healthcare Provider,9309.0,[Theft],Desktop Computer
35,TX,Healthcare Provider,900.0,[Theft],Laptop
36,IL,Healthcare Provider,812.0,[Theft],Laptop
37,TX,Healthcare Provider,689.0,[Theft],Other
38,CA,Healthcare Provider,7300.0,[Theft],Laptop
39,IL,Healthcare Provider,1300.0,[Theft],Other
40,IL,Healthcare Provider,1300.0,[Theft],Paper/Films
41,UT,Business Associate,5700.0,[Theft],Other
42,AZ,Healthcare Provider,1100.0,[Theft],Laptop
43,RI,Business Associate,528.0,[Other],Paper/Films
44,PR,Business Associate,605.0,[Theft],Paper/Films
45,PR,Business Associate,1907.0,[Theft],Paper/Films
46,FL,Healthcare Provider,8000.0,[Theft],Desktop Computer
47,TN,Health Plan,3900.0,[Theft],Paper/Films
48,CA,Healthcare Provider,532.0,[Other],Desktop Computer
49,NM,Healthcare Provider,1900.0,[Other],Desktop Computer
50,CA,Healthcare Provider,3500.0,[Theft],Network Server
51,NY,Healthcare Provider,500.0,[Theft],Paper/Films
52,FL,Healthcare Provider,12580.0,[Theft],Laptop
53,WI,Health Plan,9500.0,[Theft],Laptop
54,NC,Healthcare Provider,554.0,[Theft],Paper/Films
55,NY,Healthcare Provider,625.0,[Theft],Laptop
56,TX,Healthcare Provider,21000.0,[Theft],Other
57,TX,Healthcare Provider,21000.0,[Theft],Other Portable Electronic Device
58,FL,Healthcare Provider,3800.0,[Other],Paper/Films
59,WA,Healthcare Provider,5080.0,[Theft],Laptop
60,FL,Healthcare Provider,2600.0,[Theft],Laptop
61,CT,Healthcare Provider,957.0,[Hacking/IT Incident],Network Server
62,AL,Healthcare Provider,2465.0,[Theft],Laptop
63,AZ,Healthcare Provider,2773.0,[Theft],Other Portable Electronic Device
64,PA,Healthcare Provider,8000.0,"[Loss, Theft]",Paper/Films
65,IL,Healthcare Provider,6800.0,[Loss],Paper/Films
66,MI,Healthcare Provider,83945.0,[Other],Other
67,TX,Healthcare Provider,955.0,[Theft],Laptop
68,GA,Business Associate,660.0,[Other],Paper/Films
69,NY,Health Plan,344579.0,[Theft],Other
70,WI,Healthcare Provider,600.0,[Other],Other
71,CT,Healthcare Provider,54165.0,[Theft],Laptop
72,MA,Healthcare Provider,3594.0,[Theft],Laptop
73,RI,Health Plan,12000.0,[Theft],Paper/Films
74,SC,Health Plan,2850.0,[Improper Disposal],Paper/Films
75,CA,Healthcare Provider,22012.0,[Theft],Desktop Computer
76,CA,Healthcare Provider,5450.0,[Theft],Laptop
77,KY,Healthcare Provider,5148.0,[Theft],Other
78,KY,Healthcare Provider,5148.0,[Theft],Other Portable Electronic Device
79,MN,Health Plan,735.0,[Theft],Other
80,MN,Health Plan,735.0,[Theft],Paper/Films
81,VA,Business Associate,1874.0,[Theft],Other
82,TX,Healthcare Provider,1430.0,"[Improper Disposal, Loss]",Paper/Films
83,VA,Healthcare Provider,500.0,[Theft],Desktop Computer
84,VA,Healthcare Provider,500.0,[Theft],Laptop
85,IL,Business Associate,180111.0,[Theft],Other
86,IL,Business Associate,180111.0,[Theft],Other Portable Electronic Device
87,FL,Healthcare Provider,568.0,[Theft],Paper/Films
88,CO,Healthcare Provider,649.0,[Theft],Paper/Films
89,TX,Healthcare Provider,4200.0,[Theft],Laptop
90,DC,Healthcare Provider,2416.0,"[Other, Theft]",Email
91,DC,Healthcare Provider,2416.0,"[Other, Theft]",Other Portable Electronic Device
92,CA,Healthcare Provider,40000.0,[Theft],Network Server
93,TX,Business Associate,656.0,[Theft],Laptop
94,SC,Healthcare Provider,653.0,[Theft],Laptop
95,NY,Healthcare Provider,2628.0,[Other],Paper/Films
96,NC,Health Plan,5220.0,[Loss],Other
97,TX,Healthcare Provider,4083.0,[Improper Disposal],Paper/Films
98,IL,Healthcare Provider,1000.0,[Theft],Laptop
99,KS,Healthcare Provider,1105.0,[Theft],Laptop
100,KY,Healthcare Provider,708.0,[Hacking/IT Incident],Network Server
101,OH,Healthcare Provider,60998.0,[Theft],Laptop
102,FL,Health Plan,1220000.0,[Theft],Laptop
103,MI,Healthcare Provider,2300.0,[Theft],Laptop
104,PA,Business Associate,130495.0,[Theft],Other
105,MN,Health Plan,16291.0,[Other],Paper/Films
106,TN,Healthcare Provider,1745.0,[Loss],Laptop
107,MA,Business Associate,10515.0,[Theft],Laptop
108,NY,Health Plan,1020.0,[Theft],Desktop Computer
109,NY,Health Plan,1020.0,[Theft],Email
110,NY,Health Plan,1020.0,[Theft],Laptop
111,NY,Health Plan,1020.0,[Theft],Network Server
112,OH,Healthcare Provider,1001.0,[Other],Email
113,KY,Healthcare Provider,2027.0,[Theft],Laptop
114,TX,Healthcare Provider,600.0,[Theft],Network Server
115,GA,Business Associate,14000.0,[Loss],Other
116,NV,Healthcare Provider,7526.0,[Theft],Network Server
117,PA,Business Associate,937.0,[Other],Email
118,AZ,Healthcare Provider,5893.0,[Theft],Laptop
119,CA,Healthcare Provider,1000.0,[Other],Paper/Films
120,TN,Healthcare Provider,1537.0,[Theft],Desktop Computer
121,TN,Healthcare Provider,1537.0,[Theft],Paper/Films
122,CA,Business Associate,29000.0,"[Loss, Other]",Other
123,CA,Business Associate,29000.0,"[Loss, Other]",Other Portable Electronic Device
124,NY,Healthcare Provider,2563.0,[Theft],Other Portable Electronic Device
125,NY,Healthcare Provider,800.0,[Theft],Other
126,NY,Healthcare Provider,800.0,[Theft],Other Portable Electronic Device
127,NM,Healthcare Provider,3830.0,[Theft],Laptop
128,FL,Healthcare Provider,2047.0,[Other],Paper/Films
129,CO,Business Associate,105470.0,[Theft],Desktop Computer
130,VA,Healthcare Provider,669.0,[Theft],Other Portable Electronic Device
131,MN,Business Associate,1097.0,[Other],Paper/Films
132,PA,Business Associate,800000.0,[Loss],Electronic Medical Record
133,PA,Business Associate,800000.0,[Loss],Other
134,PA,Business Associate,800000.0,[Loss],Other Portable Electronic Device
135,NY,Healthcare Provider,23753.0,[Theft],Desktop Computer
136,OH,Business Associate,1200.0,[Improper Disposal],Paper/Films
137,TX,Healthcare Provider,27000.0,[Hacking/IT Incident],Network Server
138,DC,Health Plan,540.0,[Theft],Laptop
139,NY,Healthcare Provider,16820.0,[Theft],Desktop Computer
140,TX,Healthcare Provider,6873.0,[Theft],Desktop Computer
141,TX,Healthcare Provider,1646.0,[Theft],Laptop
142,NY,Business Associate,2631.0,[Theft],Paper/Films
143,NC,Healthcare Provider,1590.0,[Theft],Paper/Films
144,IN,Health Plan,31700.0,[Hacking/IT Incident],Network Server
145,TX,Healthcare Provider,694.0,[Theft],Laptop
146,OH,Healthcare Provider,1309.0,[Other],Laptop
147,PA,Health Plan,560.0,[Other],Other
148,KY,Healthcare Provider,2089.0,[Theft],Laptop
149,GA,Business Associate,11440.0,[Other],Other
150,GA,Business Associate,11440.0,[Other],Other Portable Electronic Device
151,IL,Healthcare Provider,657.0,"[Loss, Theft]",Paper/Films
152,TX,Healthcare Provider,25000.0,[Theft],Network Server
153,OH,Healthcare Provider,13867.0,[Theft],Laptop
154,MO,Healthcare Provider,1907.0,[Improper Disposal],Paper/Films
155,PA,Healthcare Provider,21000.0,[Theft],Laptop
156,ID,Business Associate,5500.0,[Loss],Other
157,WA,Healthcare Provider,2698.0,[Theft],Desktop Computer
158,CA,Healthcare Provider,10100.0,[Theft],Desktop Computer
159,TN,Healthcare Provider,1711.0,[Loss],Other
160,TN,Healthcare Provider,1711.0,[Loss],Other Portable Electronic Device
161,CT,Healthcare Provider,1000.0,[Theft],Laptop
162,OR,Healthcare Provider,4328.0,[Theft],Desktop Computer
163,OR,Healthcare Provider,4328.0,[Theft],Laptop
164,OR,Healthcare Provider,4328.0,[Theft],Other
165,OR,Healthcare Provider,4328.0,[Theft],Other Portable Electronic Device
166,IL,Healthcare Provider,7081.0,[Theft],Laptop
167,MA,Business Associate,24750.0,[Theft],Paper/Films
168,NM,Healthcare Provider,1000.0,[Theft],Other
169,NM,Healthcare Provider,1000.0,[Theft],Other Portable Electronic Device
170,NY,Business Associate,956.0,[Theft],Other
171,NY,Business Associate,956.0,[Theft],Other Portable Electronic Device
172,NY,Business Associate,3630.0,[Theft],Other Portable Electronic Device
173,NY,Healthcare Provider,1200.0,[Loss],Other
174,NY,Healthcare Provider,1200.0,[Loss],Other Portable Electronic Device
175,PA,Business Associate,22642.0,[Other],Network Server
176,NY,Healthcare Provider,857.0,[Loss],Other Portable Electronic Device
177,VA,Healthcare Provider,2739.0,[Theft],Laptop
178,RI,Healthcare Provider,1361.0,[Theft],Paper/Films
179,NV,Healthcare Provider,507.0,[Theft],Paper/Films
180,IA,Healthcare Provider,19222.0,[Loss],Other Portable Electronic Device
181,IN,Healthcare Provider,2000.0,[Theft],Desktop Computer
182,IN,Healthcare Provider,2000.0,[Theft],Laptop
183,CA,Healthcare Provider,33000.0,[Theft],Paper/Films
184,KS,Healthcare Provider,1200.0,[Theft],Laptop
185,KS,Healthcare Provider,1200.0,[Theft],Paper/Films
186,SC,Business Associate,1270.0,[Other],Paper/Films
187,NY,Healthcare Provider,9000.0,[Theft],Desktop Computer
188,AK,Business Associate,2000.0,[Theft],Other
189,AK,Business Associate,2000.0,[Theft],Other Portable Electronic Device
190,IN,Healthcare Provider,1199.0,[Theft],Laptop
191,CA,Business Associate,1474.0,[Theft],Other
192,CA,Business Associate,1474.0,[Theft],Other Portable Electronic Device
193,CA,Business Associate,1474.0,[Theft],Other
194,CA,Business Associate,1474.0,[Theft],Other Portable Electronic Device
195,NY,Healthcare Provider,6800.0,[Theft],Network Server
196,IL,Healthcare Provider,967.0,[Improper Disposal],Paper/Films
197,OK,Healthcare Provider,19200.0,[Hacking/IT Incident],Desktop Computer
198,CA,Healthcare Provider,928.0,[Theft],Desktop Computer
199,MA,Business Associate,11000.0,[Improper Disposal],Paper/Films
200,TX,Healthcare Provider,4700.0,[Theft],Laptop
201,TX,Healthcare Provider,4700.0,[Theft],Network Server
202,KY,Healthcare Provider,2200.0,[Theft],Paper/Films
203,NY,Healthcare Provider,578.0,[Theft],Laptop
204,MD,Health Plan,692.0,[Other],Other
205,TX,Healthcare Provider,585.0,[Theft],Laptop
206,UT,Business Associate,1298.0,[Other],Desktop Computer
207,UT,Business Associate,1298.0,[Other],Paper/Films
208,WA,Healthcare Provider,9493.0,[Hacking/IT Incident],Network Server
209,AR,Healthcare Provider,1000.0,[Theft],Other
210,AR,Healthcare Provider,1000.0,[Theft],Other Portable Electronic Device
211,CO,Healthcare Provider,2500.0,[Theft],Other
212,TN,Health Plan,1023209.0,[Theft],Other
213,CA,Healthcare Provider,716.0,[Loss],Paper/Films
214,CT,Health Plan,2345.0,[Unauthorized Access/Disclosure],Network Server
215,MS,Healthcare Provider,1104.0,[Theft],Desktop Computer
216,PR,Business Associate,115000.0,[Unauthorized Access/Disclosure],Other
217,PR,Business Associate,115000.0,[Unauthorized Access/Disclosure],Other Portable Electronic Device
218,CT,Healthcare Provider,12000.0,[Theft],Laptop
219,NE,Healthcare Provider,1550.0,[Theft],Desktop Computer
220,IN,Healthcare Provider,845.0,[Unauthorized Access/Disclosure],Paper/Films
221,NY,Healthcare Provider,535.0,[Theft],Laptop
222,MI,Healthcare Provider,3700.0,[Theft],Laptop
223,MO,Healthcare Provider,1400.0,[Theft],Laptop
224,FL,Healthcare Provider,1500.0,[Theft],Paper/Films
225,NY,Business Associate,1744.0,[Theft],Network Server
226,CA,Healthcare Provider,771.0,[Unauthorized Access/Disclosure],Paper/Films
227,OK,Healthcare Provider,1950.0,"[Improper Disposal, Loss, Theft]",Paper/Films
228,NY,Healthcare Provider,542.0,[Theft],Desktop Computer
229,PA,Healthcare Provider,613.0,[Theft],Desktop Computer
230,TN,Healthcare Provider,8200.0,[Improper Disposal],Paper/Films
231,MI,Business Associate,9475.0,[Unauthorized Access/Disclosure],Paper/Films
232,TX,Healthcare Provider,800.0,[Theft],Desktop Computer
233,MD,Healthcare Provider,1000.0,[Hacking/IT Incident],Desktop Computer
234,MD,Healthcare Provider,1000.0,[Hacking/IT Incident],Network Server
235,PA,Business Associate,1085.0,[Unauthorized Access/Disclosure],Network Server
236,IL,Healthcare Provider,556.0,[Theft],Desktop Computer
237,WI,Healthcare Provider,3288.0,[Theft],Laptop
238,OH,Healthcare Provider,1000.0,[Improper Disposal],Paper/Films
239,CA,Healthcare Provider,1250.0,[Theft],Other
240,CA,Healthcare Provider,1250.0,[Theft],Other Portable Electronic Device
241,IN,Business Associate,757.0,[Theft],Laptop
242,IN,Business Associate,585.0,[Unauthorized Access/Disclosure],Other
243,PA,Healthcare Provider,2928.0,[Theft],Email
244,MN,Healthcare Provider,3159.0,[Theft],Laptop
245,MD,Business Associate,800.0,[Theft],Paper/Films
246,KY,Healthcare Provider,24600.0,"[Loss, Theft]",Other
247,KY,Healthcare Provider,24600.0,"[Loss, Theft]",Other Portable Electronic Device
248,PA,Health Plan,808.0,[Loss],Other
249,PA,Health Plan,808.0,[Loss],Other Portable Electronic Device
250,AL,Healthcare Provider,2000.0,[Theft],Other
251,AL,Healthcare Provider,2000.0,[Theft],Other Portable Electronic Device
252,FL,Healthcare Provider,156000.0,[Theft],Network Server
253,OH,Healthcare Provider,501.0,[Theft],Desktop Computer
254,OH,Healthcare Provider,501.0,[Theft],Laptop
255,NH,Healthcare Provider,231400.0,[Hacking/IT Incident],Network Server
256,FL,Healthcare Provider,2200.0,[Theft],Laptop
257,IN,Healthcare Provider,1848.0,[Hacking/IT Incident],Email
258,IN,Healthcare Provider,1848.0,[Hacking/IT Incident],Network Server
259,VA,Healthcare Provider,11982.0,[Theft],Laptop
260,WA,Healthcare Clearing House,1250.0,[Theft],Desktop Computer
261,SC,Health Plan,5596.0,[Theft],Desktop Computer
262,MI,Healthcare Provider,656.0,[Theft],Desktop Computer
263,MI,Healthcare Provider,656.0,[Theft],Laptop
264,TX,Business Associate,16200.0,[Loss],Other
265,TX,Business Associate,16200.0,[Loss],Other Portable Electronic Device
266,MO,Business Associate,4800.0,[Theft],Other
267,WA,Healthcare Provider,12009.0,[Theft],Other
268,WA,Healthcare Provider,12009.0,[Theft],Other Portable Electronic Device
269,TX,Healthcare Provider,4486.0,[Theft],Laptop
270,TX,Healthcare Provider,8241.0,[Theft],Other
271,TX,Healthcare Provider,8241.0,[Theft],Other Portable Electronic Device
272,TN,Healthcare Provider,500.0,[Theft],Desktop Computer
273,KY,Business Associate,18871.0,[Hacking/IT Incident],Network Server
274,CO,Healthcare Provider,546.0,[Theft],Paper/Films
275,MT,Healthcare Provider,37000.0,[Theft],Laptop
276,WA,Healthcare Provider,3100.0,[Theft],Paper/Films
277,MO,Healthcare Provider,800.0,[Hacking/IT Incident],Desktop Computer
278,NJ,Business Associate,1700000.0,[Theft],Electronic Medical Record
279,NJ,Business Associate,1700000.0,[Theft],Other
280,CA,Healthcare Provider,2250.0,[Unauthorized Access/Disclosure],Other
281,TX,Healthcare Provider,9922.0,"[Loss, Theft]",Other
282,TX,Healthcare Provider,9922.0,"[Loss, Theft]",Other Portable Electronic Device
283,FL,Business Associate,2700.0,[Theft],Other
284,FL,Business Associate,2700.0,[Theft],Other Portable Electronic Device
285,WV,Business Associate,3655.0,[Unauthorized Access/Disclosure],Network Server
286,AZ,Healthcare Provider,2291.0,[Loss],Other
287,AZ,Healthcare Provider,2291.0,[Loss],Other Portable Electronic Device
288,MI,Healthcare Provider,2777.0,[Loss],Other
289,MI,Healthcare Provider,2777.0,[Loss],Other Portable Electronic Device
290,AZ,Business Associate,4500.0,[Unauthorized Access/Disclosure],Paper/Films
291,FL,Health Plan,7366.0,[Unknown],Other
292,MA,Healthcare Provider,942.0,[Unauthorized Access/Disclosure],Desktop Computer
293,KY,Healthcare Provider,8845.0,[Theft],Laptop
294,OK,Healthcare Provider,600.0,[Theft],Desktop Computer
295,OK,Healthcare Provider,600.0,[Theft],Other
296,OK,Healthcare Provider,600.0,[Theft],Other Portable Electronic Device
297,MD,Business Associate,765.0,[Unauthorized Access/Disclosure],Paper/Films
298,TX,Healthcare Provider,654.0,[Unknown],Electronic Medical Record
299,AL,Healthcare Provider,20744.0,[Theft],Desktop Computer
300,AL,Healthcare Provider,20744.0,[Theft],Network Server
301,AL,Healthcare Provider,20744.0,[Theft],Other
302,AL,Healthcare Provider,20744.0,[Theft],Other Portable Electronic Device
303,NY,Healthcare Provider,670.0,[Theft],Desktop Computer
304,CA,Healthcare Provider,514330.0,[Theft],Desktop Computer
305,WV,Healthcare Provider,1470.0,[Unauthorized Access/Disclosure],Paper/Films
306,CA,Healthcare Provider,667.0,[Theft],Laptop
307,AK,Business Associate,1700.0,[Theft],Laptop
308,AZ,Healthcare Provider,635.0,[Theft],Other
309,AZ,Healthcare Provider,635.0,[Theft],Other Portable Electronic Device
310,AZ,Healthcare Provider,10000.0,[Theft],Other
311,AZ,Healthcare Provider,10000.0,[Theft],Other Portable Electronic Device
312,CT,Business Associate,93500.0,[Theft],Other
313,OK,Healthcare Provider,84000.0,[Theft],Network Server
314,MO,Health Plan,935.0,[Unauthorized Access/Disclosure],Other
315,OK,Healthcare Provider,132940.0,[Theft],Laptop
316,OK,Healthcare Provider,132940.0,[Theft],Paper/Films
317,SC,Healthcare Provider,2717.0,[Improper Disposal],Paper/Films
318,MN,Healthcare Provider,1215.0,[Loss],Paper/Films
319,NY,Business Associate,1900000.0,[Unknown],Other
320,AZ,Healthcare Provider,566.0,[Theft],Paper/Films
321,IL,Business Associate,675.0,[Unauthorized Access/Disclosure],Other
322,WY,Healthcare Provider,15000.0,[Theft],Desktop Computer
323,NC,Healthcare Provider,6000.0,[Hacking/IT Incident],Network Server
324,IL,Healthcare Provider,1070.0,[Hacking/IT Incident],Desktop Computer
325,IL,Healthcare Provider,1070.0,[Hacking/IT Incident],Email
326,IL,Healthcare Provider,1070.0,[Hacking/IT Incident],Laptop
327,IL,Healthcare Provider,1070.0,[Hacking/IT Incident],Network Server
328,IL,Healthcare Provider,845.0,[Hacking/IT Incident],Desktop Computer
329,IL,Healthcare Provider,845.0,[Hacking/IT Incident],Email
330,IL,Healthcare Provider,845.0,[Hacking/IT Incident],Laptop
331,IL,Healthcare Provider,845.0,[Hacking/IT Incident],Network Server
332,IL,Healthcare Provider,686.0,[Hacking/IT Incident],Desktop Computer
333,IL,Healthcare Provider,686.0,[Hacking/IT Incident],Email
334,IL,Healthcare Provider,686.0,[Hacking/IT Incident],Laptop
335,IL,Healthcare Provider,686.0,[Hacking/IT Incident],Network Server
336,AZ,Health Plan,9393.0,[Hacking/IT Incident],Desktop Computer
337,AZ,Health Plan,9393.0,[Hacking/IT Incident],Email
338,AZ,Health Plan,9393.0,[Hacking/IT Incident],Laptop
339,AZ,Health Plan,9393.0,[Hacking/IT Incident],Network Server
340,IL,Healthcare Provider,532.0,[Hacking/IT Incident],Desktop Computer
341,IL,Healthcare Provider,532.0,[Hacking/IT Incident],Email
342,IL,Healthcare Provider,532.0,[Hacking/IT Incident],Laptop
343,IL,Healthcare Provider,532.0,[Hacking/IT Incident],Network Server
344,OH,Healthcare Provider,500.0,[Improper Disposal],Other
345,NH,Healthcare Provider,5960.0,[Theft],Laptop

In [24]:
kolom = df_exploded['Type of Breach Code']
kolom.mean(), kolom.median(), kolom.mode()[0]
kolom.var(), kolom.std()
kolom.quantile(0.25), kolom.quantile(0.75)
df_exploded['Type of Breach Code'].describe() #ngejelasin tipe datanya

count    1852.000000
mean        2.857991
std         2.042981
min         1.000000
25%         1.000000
50%         2.000000
75%         5.000000
max         6.000000
Name: Type of Breach Code, dtype: float64

**c) Mean, Median, Modus kolom 'Type of Breach'**

In [25]:
type_mapping1 = {
    'Paper/Films': 1,
    'Network Server': 2,
    'Other': 3,
    'Other Portable Electronic Device': 4,
    'Laptop': 5,
    'Desktop Computer': 6,
    'Electronic Medical Record': 7,
    'Email': 8
}
df_exploded['Location of Breached Information Code'] = df_exploded['Location of Breached Information'].map(type_mapping1) #di apply ke df_exploded
df_exploded.head()
df_exploded.drop(['Location of Breached Information Code'],axis=1) #ini tadi ke double run jadi di hapus tiap di run code nya

,State,Covered Entity Type,Individuals Affected,Type of Breach,Location of Breached Information,Type of Breach Code
0,TX,Healthcare Provider,1000.0,[Theft],Paper/Films,1.0
1,MO,Healthcare Provider,1000.0,[Theft],Network Server,1.0
2,AK,Healthcare Provider,501.0,[Theft],Other,1.0
3,AK,Healthcare Provider,501.0,[Theft],Other Portable Electronic Device,1.0
4,DC,Health Plan,3800.0,[Loss],Laptop,2.0
5,CA,Healthcare Provider,5166.0,[Theft],Desktop Computer,1.0
6,CA,Healthcare Provider,5257.0,[Theft],Desktop Computer,1.0
7,CA,Healthcare Provider,857.0,[Theft],Desktop Computer,1.0
8,CA,Healthcare Provider,6145.0,[Theft],Desktop Computer,1.0
9,CA,Healthcare Provider,952.0,[Theft],Desktop Computer,1.0
10,CA,Healthcare Provider,5900.0,[Theft],Laptop,1.0
11,PA,Healthcare Provider,943.0,[Theft],Laptop,1.0
12,TN,Business Associate,6400.0,[Theft],Laptop,1.0
13,VA,Business Associate,83000.0,[Other],Paper/Films,3.0
14,CA,Healthcare Provider,596.0,[Theft],Other,1.0
15,NC,Business Associate,2000.0,[Theft],Desktop Computer,1.0
16,NC,Business Associate,2000.0,[Theft],Electronic Medical Record,1.0
17,NC,Business Associate,2000.0,[Theft],Network Server,1.0
18,MI,Healthcare Provider,646.0,[Theft],Desktop Computer,1.0
19,MI,Healthcare Provider,646.0,[Theft],Laptop,1.0
20,MI,Healthcare Provider,10000.0,[Theft],Other Portable Electronic Device,1.0
21,CA,Healthcare Provider,610.0,[Other],Email,3.0
22,MA,Business Associate,1860.0,[Theft],Electronic Medical Record,1.0
23,MA,Business Associate,1860.0,[Theft],Other,1.0
24,MA,Business Associate,1860.0,[Theft],Other Portable Electronic Device,1.0
25,DC,Business Associate,3400.0,[Theft],Paper/Films,1.0
26,MA,Healthcare Provider,1076.0,[Theft],Other,1.0
27,MD,Business Associate,15000.0,[Theft],Paper/Films,1.0
28,CA,Healthcare Provider,15500.0,[Theft],Other,1.0
29,CA,Healthcare Provider,15500.0,[Theft],Other Portable Electronic Device,1.0
30,ID,Business Associate,2562.0,[Theft],Other,1.0
31,MI,Healthcare Provider,10000.0,[Theft],Other,1.0
32,TX,Healthcare Provider,3800.0,[Loss],Other,2.0
33,TX,Healthcare Provider,3800.0,[Loss],Other Portable Electronic Device,2.0
34,MO,Healthcare Provider,9309.0,[Theft],Desktop Computer,1.0
35,TX,Healthcare Provider,900.0,[Theft],Laptop,1.0
36,IL,Healthcare Provider,812.0,[Theft],Laptop,1.0
37,TX,Healthcare Provider,689.0,[Theft],Other,1.0
38,CA,Healthcare Provider,7300.0,[Theft],Laptop,1.0
39,IL,Healthcare Provider,1300.0,[Theft],Other,1.0
40,IL,Healthcare Provider,1300.0,[Theft],Paper/Films,1.0
41,UT,Business Associate,5700.0,[Theft],Other,1.0
42,AZ,Healthcare Provider,1100.0,[Theft],Laptop,1.0
43,RI,Business Associate,528.0,[Other],Paper/Films,3.0
44,PR,Business Associate,605.0,[Theft],Paper/Films,1.0
45,PR,Business Associate,1907.0,[Theft],Paper/Films,1.0
46,FL,Healthcare Provider,8000.0,[Theft],Desktop Computer,1.0
47,TN,Health Plan,3900.0,[Theft],Paper/Films,1.0
48,CA,Healthcare Provider,532.0,[Other],Desktop Computer,3.0
49,NM,Healthcare Provider,1900.0,[Other],Desktop Computer,3.0
50,CA,Healthcare Provider,3500.0,[Theft],Network Server,1.0
51,NY,Healthcare Provider,500.0,[Theft],Paper/Films,1.0
52,FL,Healthcare Provider,12580.0,[Theft],Laptop,1.0
53,WI,Health Plan,9500.0,[Theft],Laptop,1.0
54,NC,Healthcare Provider,554.0,[Theft],Paper/Films,1.0
55,NY,Healthcare Provider,625.0,[Theft],Laptop,1.0
56,TX,Healthcare Provider,21000.0,[Theft],Other,1.0
57,TX,Healthcare Provider,21000.0,[Theft],Other Portable Electronic Device,1.0
58,FL,Healthcare Provider,3800.0,[Other],Paper/Films,3.0
59,WA,Healthcare Provider,5080.0,[Theft],Laptop,1.0
60,FL,Healthcare Provider,2600.0,[Theft],Laptop,1.0
61,CT,Healthcare Provider,957.0,[Hacking/IT Incident],Network Server,4.0
62,AL,Healthcare Provider,2465.0,[Theft],Laptop,1.0
63,AZ,Healthcare Provider,2773.0,[Theft],Other Portable Electronic Device,1.0
64,PA,Healthcare Provider,8000.0,"[Loss, Theft]",Paper/Films,2.0
65,IL,Healthcare Provider,6800.0,[Loss],Paper/Films,2.0
66,MI,Healthcare Provider,83945.0,[Other],Other,3.0
67,TX,Healthcare Provider,955.0,[Theft],Laptop,1.0
68,GA,Business Associate,660.0,[Other],Paper/Films,3.0
69,NY,Health Plan,344579.0,[Theft],Other,1.0
70,WI,Healthcare Provider,600.0,[Other],Other,3.0
71,CT,Healthcare Provider,54165.0,[Theft],Laptop,1.0
72,MA,Healthcare Provider,3594.0,[Theft],Laptop,1.0
73,RI,Health Plan,12000.0,[Theft],Paper/Films,1.0
74,SC,Health Plan,2850.0,[Improper Disposal],Paper/Films,5.0
75,CA,Healthcare Provider,22012.0,[Theft],Desktop Computer,1.0
76,CA,Healthcare Provider,5450.0,[Theft],Laptop,1.0
77,KY,Healthcare Provider,5148.0,[Theft],Other,1.0
78,KY,Healthcare Provider,5148.0,[Theft],Other Portable Electronic Device,1.0
79,MN,Health Plan,735.0,[Theft],Other,1.0
80,MN,Health Plan,735.0,[Theft],Paper/Films,1.0
81,VA,Business Associate,1874.0,[Theft],Other,1.0
82,TX,Healthcare Provider,1430.0,"[Improper Disposal, Loss]",Paper/Films,5.0
83,VA,Healthcare Provider,500.0,[Theft],Desktop Computer,1.0
84,VA,Healthcare Provider,500.0,[Theft],Laptop,1.0
85,IL,Business Associate,180111.0,[Theft],Other,1.0
86,IL,Business Associate,180111.0,[Theft],Other Portable Electronic Device,1.0
87,FL,Healthcare Provider,568.0,[Theft],Paper/Films,1.0
88,CO,Healthcare Provider,649.0,[Theft],Paper/Films,1.0
89,TX,Healthcare Provider,4200.0,[Theft],Laptop,1.0
90,DC,Healthcare Provider,2416.0,"[Other, Theft]",Email,3.0
91,DC,Healthcare Provider,2416.0,"[Other, Theft]",Other Portable Electronic Device,3.0
92,CA,Healthcare Provider,40000.0,[Theft],Network Server,1.0
93,TX,Business Associate,656.0,[Theft],Laptop,1.0
94,SC,Healthcare Provider,653.0,[Theft],Laptop,1.0
95,NY,Healthcare Provider,2628.0,[Other],Paper/Films,3.0
96,NC,Health Plan,5220.0,[Loss],Other,2.0
97,TX,Healthcare Provider,4083.0,[Improper Disposal],Paper/Films,5.0
98,IL,Healthcare Provider,1000.0,[Theft],Laptop,1.0
99,KS,Healthcare Provider,1105.0,[Theft],Laptop,1.0
100,KY,Healthcare Provider,708.0,[Hacking/IT Incident],Network Server,4.0
101,OH,Healthcare Provider,60998.0,[Theft],Laptop,1.0
102,FL,Health Plan,1220000.0,[Theft],Laptop,1.0
103,MI,Healthcare Provider,2300.0,[Theft],Laptop,1.0
104,PA,Business Associate,130495.0,[Theft],Other,1.0
105,MN,Health Plan,16291.0,[Other],Paper/Films,3.0
106,TN,Healthcare Provider,1745.0,[Loss],Laptop,2.0
107,MA,Business Associate,10515.0,[Theft],Laptop,1.0
108,NY,Health Plan,1020.0,[Theft],Desktop Computer,1.0
109,NY,Health Plan,1020.0,[Theft],Email,1.0
110,NY,Health Plan,1020.0,[Theft],Laptop,1.0
111,NY,Health Plan,1020.0,[Theft],Network Server,1.0
112,OH,Healthcare Provider,1001.0,[Other],Email,3.0
113,KY,Healthcare Provider,2027.0,[Theft],Laptop,1.0
114,TX,Healthcare Provider,600.0,[Theft],Network Server,1.0
115,GA,Business Associate,14000.0,[Loss],Other,2.0
116,NV,Healthcare Provider,7526.0,[Theft],Network Server,1.0
117,PA,Business Associate,937.0,[Other],Email,3.0
118,AZ,Healthcare Provider,5893.0,[Theft],Laptop,1.0
119,CA,Healthcare Provider,1000.0,[Other],Paper/Films,3.0
120,TN,Healthcare Provider,1537.0,[Theft],Desktop Computer,1.0
121,TN,Healthcare Provider,1537.0,[Theft],Paper/Films,1.0
122,CA,Business Associate,29000.0,"[Loss, Other]",Other,2.0
123,CA,Business Associate,29000.0,"[Loss, Other]",Other Portable Electronic Device,2.0
124,NY,Healthcare Provider,2563.0,[Theft],Other Portable Electronic Device,1.0
125,NY,Healthcare Provider,800.0,[Theft],Other,1.0
126,NY,Healthcare Provider,800.0,[Theft],Other Portable Electronic Device,1.0
127,NM,Healthcare Provider,3830.0,[Theft],Laptop,1.0
128,FL,Healthcare Provider,2047.0,[Other],Paper/Films,3.0
129,CO,Business Associate,105470.0,[Theft],Desktop Computer,1.0
130,VA,Healthcare Provider,669.0,[Theft],Other Portable Electronic Device,1.0
131,MN,Business Associate,1097.0,[Other],Paper/Films,3.0
132,PA,Business Associate,800000.0,[Loss],Electronic Medical Record,2.0
133,PA,Business Associate,800000.0,[Loss],Other,2.0
134,PA,Business Associate,800000.0,[Loss],Other Portable Electronic Device,2.0
135,NY,Healthcare Provider,23753.0,[Theft],Desktop Computer,1.0
136,OH,Business Associate,1200.0,[Improper Disposal],Paper/Films,5.0
137,TX,Healthcare Provider,27000.0,[Hacking/IT Incident],Network Server,4.0
138,DC,Health Plan,540.0,[Theft],Laptop,1.0
139,NY,Healthcare Provider,16820.0,[Theft],Desktop Computer,1.0
140,TX,Healthcare Provider,6873.0,[Theft],Desktop Computer,1.0
141,TX,Healthcare Provider,1646.0,[Theft],Laptop,1.0
142,NY,Business Associate,2631.0,[Theft],Paper/Films,1.0
143,NC,Healthcare Provider,1590.0,[Theft],Paper/Films,1.0
144,IN,Health Plan,31700.0,[Hacking/IT Incident],Network Server,4.0
145,TX,Healthcare Provider,694.0,[Theft],Laptop,1.0
146,OH,Healthcare Provider,1309.0,[Other],Laptop,3.0
147,PA,Health Plan,560.0,[Other],Other,3.0
148,KY,Healthcare Provider,2089.0,[Theft],Laptop,1.0
149,GA,Business Associate,11440.0,[Other],Other,3.0
150,GA,Business Associate,11440.0,[Other],Other Portable Electronic Device,3.0
151,IL,Healthcare Provider,657.0,"[Loss, Theft]",Paper/Films,2.0
152,TX,Healthcare Provider,25000.0,[Theft],Network Server,1.0
153,OH,Healthcare Provider,13867.0,[Theft],Laptop,1.0
154,MO,Healthcare Provider,1907.0,[Improper Disposal],Paper/Films,5.0
155,PA,Healthcare Provider,21000.0,[Theft],Laptop,1.0
156,ID,Business Associate,5500.0,[Loss],Other,2.0
157,WA,Healthcare Provider,2698.0,[Theft],Desktop Computer,1.0
158,CA,Healthcare Provider,10100.0,[Theft],Desktop Computer,1.0
159,TN,Healthcare Provider,1711.0,[Loss],Other,2.0
160,TN,Healthcare Provider,1711.0,[Loss],Other Portable Electronic Device,2.0
161,CT,Healthcare Provider,1000.0,[Theft],Laptop,1.0
162,OR,Healthcare Provider,4328.0,[Theft],Desktop Computer,1.0
163,OR,Healthcare Provider,4328.0,[Theft],Laptop,1.0
164,OR,Healthcare Provider,4328.0,[Theft],Other,1.0
165,OR,Healthcare Provider,4328.0,[Theft],Other Portable Electronic Device,1.0
166,IL,Healthcare Provider,7081.0,[Theft],Laptop,1.0
167,MA,Business Associate,24750.0,[Theft],Paper/Films,1.0
168,NM,Healthcare Provider,1000.0,[Theft],Other,1.0
169,NM,Healthcare Provider,1000.0,[Theft],Other Portable Electronic Device,1.0
170,NY,Business Associate,956.0,[Theft],Other,1.0
171,NY,Business Associate,956.0,[Theft],Other Portable Electronic Device,1.0
172,NY,Business Associate,3630.0,[Theft],Other Portable Electronic Device,1.0
173,NY,Healthcare Provider,1200.0,[Loss],Other,2.0
174,NY,Healthcare Provider,1200.0,[Loss],Other Portable Electronic Device,2.0
175,PA,Business Associate,22642.0,[Other],Network Server,3.0
176,NY,Healthcare Provider,857.0,[Loss],Other Portable Electronic Device,2.0
177,VA,Healthcare Provider,2739.0,[Theft],Laptop,1.0
178,RI,Healthcare Provider,1361.0,[Theft],Paper/Films,1.0
179,NV,Healthcare Provider,507.0,[Theft],Paper/Films,1.0
180,IA,Healthcare Provider,19222.0,[Loss],Other Portable Electronic Device,2.0
181,IN,Healthcare Provider,2000.0,[Theft],Desktop Computer,1.0
182,IN,Healthcare Provider,2000.0,[Theft],Laptop,1.0
183,CA,Healthcare Provider,33000.0,[Theft],Paper/Films,1.0
184,KS,Healthcare Provider,1200.0,[Theft],Laptop,1.0
185,KS,Healthcare Provider,1200.0,[Theft],Paper/Films,1.0
186,SC,Business Associate,1270.0,[Other],Paper/Films,3.0
187,NY,Healthcare Provider,9000.0,[Theft],Desktop Computer,1.0
188,AK,Business Associate,2000.0,[Theft],Other,1.0
189,AK,Business Associate,2000.0,[Theft],Other Portable Electronic Device,1.0
190,IN,Healthcare Provider,1199.0,[Theft],Laptop,1.0
191,CA,Business Associate,1474.0,[Theft],Other,1.0
192,CA,Business Associate,1474.0,[Theft],Other Portable Electronic Device,1.0
193,CA,Business Associate,1474.0,[Theft],Other,1.0
194,CA,Business Associate,1474.0,[Theft],Other Portable Electronic Device,1.0
195,NY,Healthcare Provider,6800.0,[Theft],Network Server,1.0
196,IL,Healthcare Provider,967.0,[Improper Disposal],Paper/Films,5.0
197,OK,Healthcare Provider,19200.0,[Hacking/IT Incident],Desktop Computer,4.0
198,CA,Healthcare Provider,928.0,[Theft],Desktop Computer,1.0
199,MA,Business Associate,11000.0,[Improper Disposal],Paper/Films,5.0
200,TX,Healthcare Provider,4700.0,[Theft],Laptop,1.0
201,TX,Healthcare Provider,4700.0,[Theft],Network Server,1.0
202,KY,Healthcare Provider,2200.0,[Theft],Paper/Films,1.0
203,NY,Healthcare Provider,578.0,[Theft],Laptop,1.0
204,MD,Health Plan,692.0,[Other],Other,3.0
205,TX,Healthcare Provider,585.0,[Theft],Laptop,1.0
206,UT,Business Associate,1298.0,[Other],Desktop Computer,3.0
207,UT,Business Associate,1298.0,[Other],Paper/Films,3.0
208,WA,Healthcare Provider,9493.0,[Hacking/IT Incident],Network Server,4.0
209,AR,Healthcare Provider,1000.0,[Theft],Other,1.0
210,AR,Healthcare Provider,1000.0,[Theft],Other Portable Electronic Device,1.0
211,CO,Healthcare Provider,2500.0,[Theft],Other,1.0
212,TN,Health Plan,1023209.0,[Theft],Other,1.0
213,CA,Healthcare Provider,716.0,[Loss],Paper/Films,2.0
214,CT,Health Plan,2345.0,[Unauthorized Access/Disclosure],Network Server,6.0
215,MS,Healthcare Provider,1104.0,[Theft],Desktop Computer,1.0
216,PR,Business Associate,115000.0,[Unauthorized Access/Disclosure],Other,6.0
217,PR,Business Associate,115000.0,[Unauthorized Access/Disclosure],Other Portable Electronic Device,6.0
218,CT,Healthcare Provider,12000.0,[Theft],Laptop,1.0
219,NE,Healthcare Provider,1550.0,[Theft],Desktop Computer,1.0
220,IN,Healthcare Provider,845.0,[Unauthorized Access/Disclosure],Paper/Films,6.0
221,NY,Healthcare Provider,535.0,[Theft],Laptop,1.0
222,MI,Healthcare Provider,3700.0,[Theft],Laptop,1.0
223,MO,Healthcare Provider,1400.0,[Theft],Laptop,1.0
224,FL,Healthcare Provider,1500.0,[Theft],Paper/Films,1.0
225,NY,Business Associate,1744.0,[Theft],Network Server,1.0
226,CA,Healthcare Provider,771.0,[Unauthorized Access/Disclosure],Paper/Films,6.0
227,OK,Healthcare Provider,1950.0,"[Improper Disposal, Loss, Theft]",Paper/Films,5.0
228,NY,Healthcare Provider,542.0,[Theft],Desktop Computer,1.0
229,PA,Healthcare Provider,613.0,[Theft],Desktop Computer,1.0
230,TN,Healthcare Provider,8200.0,[Improper Disposal],Paper/Films,5.0
231,MI,Business Associate,9475.0,[Unauthorized Access/Disclosure],Paper/Films,6.0
232,TX,Healthcare Provider,800.0,[Theft],Desktop Computer,1.0
233,MD,Healthcare Provider,1000.0,[Hacking/IT Incident],Desktop Computer,4.0
234,MD,Healthcare Provider,1000.0,[Hacking/IT Incident],Network Server,4.0
235,PA,Business Associate,1085.0,[Unauthorized Access/Disclosure],Network Server,6.0
236,IL,Healthcare Provider,556.0,[Theft],Desktop Computer,1.0
237,WI,Healthcare Provider,3288.0,[Theft],Laptop,1.0
238,OH,Healthcare Provider,1000.0,[Improper Disposal],Paper/Films,5.0
239,CA,Healthcare Provider,1250.0,[Theft],Other,1.0
240,CA,Healthcare Provider,1250.0,[Theft],Other Portable Electronic Device,1.0
241,IN,Business Associate,757.0,[Theft],Laptop,1.0
242,IN,Business Associate,585.0,[Unauthorized Access/Disclosure],Other,6.0
243,PA,Healthcare Provider,2928.0,[Theft],Email,1.0
244,MN,Healthcare Provider,3159.0,[Theft],Laptop,1.0
245,MD,Business Associate,800.0,[Theft],Paper/Films,1.0
246,KY,Healthcare Provider,24600.0,"[Loss, Theft]",Other,2.0
247,KY,Healthcare Provider,24600.0,"[Loss, Theft]",Other Portable Electronic Device,2.0
248,PA,Health Plan,808.0,[Loss],Other,2.0
249,PA,Health Plan,808.0,[Loss],Other Portable Electronic Device,2.0
250,AL,Healthcare Provider,2000.0,[Theft],Other,1.0
251,AL,Healthcare Provider,2000.0,[Theft],Other Portable Electronic Device,1.0
252,FL,Healthcare Provider,156000.0,[Theft],Network Server,1.0
253,OH,Healthcare Provider,501.0,[Theft],Desktop Computer,1.0
254,OH,Healthcare Provider,501.0,[Theft],Laptop,1.0
255,NH,Healthcare Provider,231400.0,[Hacking/IT Incident],Network Server,4.0
256,FL,Healthcare Provider,2200.0,[Theft],Laptop,1.0
257,IN,Healthcare Provider,1848.0,[Hacking/IT Incident],Email,4.0
258,IN,Healthcare Provider,1848.0,[Hacking/IT Incident],Network Server,4.0
259,VA,Healthcare Provider,11982.0,[Theft],Laptop,1.0
260,WA,Healthcare Clearing House,1250.0,[Theft],Desktop Computer,1.0
261,SC,Health Plan,5596.0,[Theft],Desktop Computer,1.0
262,MI,Healthcare Provider,656.0,[Theft],Desktop Computer,1.0
263,MI,Healthcare Provider,656.0,[Theft],Laptop,1.0
264,TX,Business Associate,16200.0,[Loss],Other,2.0
265,TX,Business Associate,16200.0,[Loss],Other Portable Electronic Device,2.0
266,MO,Business Associate,4800.0,[Theft],Other,1.0
267,WA,Healthcare Provider,12009.0,[Theft],Other,1.0
268,WA,Healthcare Provider,12009.0,[Theft],Other Portable Electronic Device,1.0
269,TX,Healthcare Provider,4486.0,[Theft],Laptop,1.0
270,TX,Healthcare Provider,8241.0,[Theft],Other,1.0
271,TX,Healthcare Provider,8241.0,[Theft],Other Portable Electronic Device,1.0
272,TN,Healthcare Provider,500.0,[Theft],Desktop Computer,1.0
273,KY,Business Associate,18871.0,[Hacking/IT Incident],Network Server,4.0
274,CO,Healthcare Provider,546.0,[Theft],Paper/Films,1.0
275,MT,Healthcare Provider,37000.0,[Theft],Laptop,1.0
276,WA,Healthcare Provider,3100.0,[Theft],Paper/Films,1.0
277,MO,Healthcare Provider,800.0,[Hacking/IT Incident],Desktop Computer,4.0
278,NJ,Business Associate,1700000.0,[Theft],Electronic Medical Record,1.0
279,NJ,Business Associate,1700000.0,[Theft],Other,1.0
280,CA,Healthcare Provider,2250.0,[Unauthorized Access/Disclosure],Other,6.0
281,TX,Healthcare Provider,9922.0,"[Loss, Theft]",Other,2.0
282,TX,Healthcare Provider,9922.0,"[Loss, Theft]",Other Portable Electronic Device,2.0
283,FL,Business Associate,2700.0,[Theft],Other,1.0
284,FL,Business Associate,2700.0,[Theft],Other Portable Electronic Device,1.0
285,WV,Business Associate,3655.0,[Unauthorized Access/Disclosure],Network Server,6.0
286,AZ,Healthcare Provider,2291.0,[Loss],Other,2.0
287,AZ,Healthcare Provider,2291.0,[Loss],Other Portable Electronic Device,2.0
288,MI,Healthcare Provider,2777.0,[Loss],Other,2.0
289,MI,Healthcare Provider,2777.0,[Loss],Other Portable Electronic Device,2.0
290,AZ,Business Associate,4500.0,[Unauthorized Access/Disclosure],Paper/Films,6.0
291,FL,Health Plan,7366.0,[Unknown],Other,NaN
292,MA,Healthcare Provider,942.0,[Unauthorized Access/Disclosure],Desktop Computer,6.0
293,KY,Healthcare Provider,8845.0,[Theft],Laptop,1.0
294,OK,Healthcare Provider,600.0,[Theft],Desktop Computer,1.0
295,OK,Healthcare Provider,600.0,[Theft],Other,1.0
296,OK,Healthcare Provider,600.0,[Theft],Other Portable Electronic Device,1.0
297,MD,Business Associate,765.0,[Unauthorized Access/Disclosure],Paper/Films,6.0
298,TX,Healthcare Provider,654.0,[Unknown],Electronic Medical Record,NaN
299,AL,Healthcare Provider,20744.0,[Theft],Desktop Computer,1.0
300,AL,Healthcare Provider,20744.0,[Theft],Network Server,1.0
301,AL,Healthcare Provider,20744.0,[Theft],Other,1.0
302,AL,Healthcare Provider,20744.0,[Theft],Other Portable Electronic Device,1.0
303,NY,Healthcare Provider,670.0,[Theft],Desktop Computer,1.0
304,CA,Healthcare Provider,514330.0,[Theft],Desktop Computer,1.0
305,WV,Healthcare Provider,1470.0,[Unauthorized Access/Disclosure],Paper/Films,6.0
306,CA,Healthcare Provider,667.0,[Theft],Laptop,1.0
307,AK,Business Associate,1700.0,[Theft],Laptop,1.0
308,AZ,Healthcare Provider,635.0,[Theft],Other,1.0
309,AZ,Healthcare Provider,635.0,[Theft],Other Portable Electronic Device,1.0
310,AZ,Healthcare Provider,10000.0,[Theft],Other,1.0
311,AZ,Healthcare Provider,10000.0,[Theft],Other Portable Electronic Device,1.0
312,CT,Business Associate,93500.0,[Theft],Other,1.0
313,OK,Healthcare Provider,84000.0,[Theft],Network Server,1.0
314,MO,Health Plan,935.0,[Unauthorized Access/Disclosure],Other,6.0
315,OK,Healthcare Provider,132940.0,[Theft],Laptop,1.0
316,OK,Healthcare Provider,132940.0,[Theft],Paper/Films,1.0
317,SC,Healthcare Provider,2717.0,[Improper Disposal],Paper/Films,5.0
318,MN,Healthcare Provider,1215.0,[Loss],Paper/Films,2.0
319,NY,Business Associate,1900000.0,[Unknown],Other,NaN
320,AZ,Healthcare Provider,566.0,[Theft],Paper/Films,1.0
321,IL,Business Associate,675.0,[Unauthorized Access/Disclosure],Other,6.0
322,WY,Healthcare Provider,15000.0,[Theft],Desktop Computer,1.0
323,NC,Healthcare Provider,6000.0,[Hacking/IT Incident],Network Server,4.0
324,IL,Healthcare Provider,1070.0,[Hacking/IT Incident],Desktop Computer,4.0

In [26]:
kolom = df_exploded['Location of Breached Information Code']
kolom.mean(), kolom.median(), kolom.mode()[0]
kolom.var(), kolom.std()
kolom.quantile(0.25), kolom.quantile(0.75)
df_exploded['Location of Breached Information Code'].describe()

count    1861.000000
mean        3.818377
std         2.240705
min         1.000000
25%         2.000000
50%         4.000000
75%         5.000000
max         8.000000
Name: Location of Breached Information Code, dtype: float64